version: "3"
services:
  app:
    image: socialworky/worky-frontend-dev:${GIT_SHA}
    restart: always
    container_name: worky-frontend
    ports:
      - ${APP_PORT}:80
    environment:
      API_URL: ${API_URL}
      BASE_URL: ${BASE_URL}
      CLIEN_ID_GOOGLE: ${CLIEN_ID_GOOGLE}
    dns:
      - 1.1.1.1
