apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: social-network-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend
        image: socialworky/worky-frontend-dev:535e8fb09ea8776ea3497c2368812ef6b619381d
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
