name: Update Container on Portainer

on:
  push:
    branches:
      - development

jobs:
  update-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NG_APP_BASE_URL: ${{ secrets.NG_APP_BASE_URL }}
          NG_APP_API_URL: ${{ secrets.NG_APP_API_URL }}
          NG_APP_CLIEN_ID_GOOGLE: ${{ secrets.NG_APP_CLIEN_ID_GOOGLE }}
          NG_APP_WSURL: ${{ secrets.NG_APP_WSURL }}
          NG_APP_OPENCAGEAPIKEY: ${{ secrets.NG_APP_OPENCAGEAPIKEY }}
          NG_APP_APIGEOLOCATIONS: ${{ secrets.NG_APP_APIGEOLOCATIONS }}
          NG_APP_APIWEATHERURL: ${{ secrets.NG_APP_APIWEATHERURL }}
          NG_APP_APIWEATHERTOKEN: ${{ secrets.NG_APP_APIWEATHERTOKEN }}
          NG_APP_APIFILESERVICE: ${{ secrets.NG_APP_APIFILESERVICE }}
          NG_APP_APIMESSAGESERVICE: ${{ secrets.NG_APP_APIMESSAGESERVICE }}
          NG_APP_APINOTIFICATIONCENTER: ${{ secrets.NG_APP_APINOTIFICATIONCENTER }}
          NG_APP_GIPHYAPIKEY: ${{ secrets.NG_APP_GIPHYAPIKEY }}
        run: |
          echo "Iniciando la construcción y el empuje de la imagen Docker..."
          docker build -t socialworky/worky-frontend-dev:${{ github.sha }} \
            --build-arg NG_APP_BASE_URL=${NG_APP_BASE_URL} \
            --build-arg NG_APP_API_URL=${NG_APP_API_URL} \
            --build-arg NG_APP_CLIEN_ID_GOOGLE=${NG_APP_CLIEN_ID_GOOGLE} \
            --build-arg NG_APP_WSURL=${NG_APP_WSURL} \
            --build-arg NG_APP_OPENCAGEAPIKEY=${NG_APP_OPENCAGEAPIKEY} \
            --build-arg NG_APP_APIGEOLOCATIONS=${NG_APP_APIGEOLOCATIONS} \
            --build-arg NG_APP_APIWEATHERURL=${NG_APP_APIWEATHERURL} \
            --build-arg NG_APP_APIWEATHERTOKEN=${NG_APP_APIWEATHERTOKEN} \
            --build-arg NG_APP_APIFILESERVICE=${NG_APP_APIFILESERVICE} \
            --build-arg NG_APP_APIMESSAGESERVICE=${NG_APP_APIMESSAGESERVICE} \
            --build-arg NG_APP_APINOTIFICATIONCENTER=${NG_APP_APINOTIFICATIONCENTER} \
            --build-arg NG_APP_GIPHYAPIKEY=${NG_APP_GIPHYAPIKEY}
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push socialworky/worky-frontend-dev:${{ github.sha }}
          echo "Construcción y empuje de la imagen Docker completados."

      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: https://portainer-dev.worky.cl
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'worky-frontend-dev'
          stack-definition: 'docker-compose-worky.dev.yml'
          image: socialworky/worky-frontend-dev:${{ github.sha }}
        env:
          GIT_SHA: ${{ github.sha }}
          
